hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://172.23.0.1:3306/shop_restful
#    Username: root
#    password: 10112002
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql:localhost:8080/shop_restful?createDatabaseIfNotExist=true}
    Username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:ABC10112002}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      org:
        hibernate:
          envers:
            default_schema = shop_restful